Create gate-controlling.js
wirenboard/wb-community pull request #2
Opened 2022-09-06 09:31 UTC by matveevrj

Скрипт для управления воротами с помощью модуля реле WB-MRM2mini

2022-09-06 12:57 UTC, aadegtyarev commented on wb-mrm2mini-gate-conrolling/gate-controlling.js
> +  if(dev ["wb-mrm2-mini_12/Input 1"] == false) {
К этому входу по схеме подключен датчик Открыто, логичнее строить алгоритм так:
Команда Открыть ворота → Ворота закрыты? → Открываем.

То есть проверять закрыты ли ворота, считывая состояние датчика Закрыто.

2022-09-06 12:57 UTC, aadegtyarev commented on wb-mrm2mini-gate-conrolling/gate-controlling.js
> +     if(dev["wb-mrm2-mini_12/Input 2"] == false) {
Аналогично с Открытием — не тот датчик смотрим

2022-09-06 12:57 UTC, aadegtyarev commented on wb-mrm2mini-gate-conrolling/gate-controlling.js
> +    }
Тут можно переписать.

Было:
```
 if(dev["wb-mrm2-mini_12/Input 1"] == true) { 
    	dev["wb-mrm2-mini_12/K1"] = false;
    }
  if(dev["wb-mrm2-mini_12/Input 2"] == true) { 
    	dev["wb-mrm2-mini_12/K2"] = false;
    }   
```

Стало:
```
dev["wb-mrm2-mini_12/K1"] = !dev["wb-mrm2-mini_12/Input 1"]
dev["wb-mrm2-mini_12/K2"] = !dev["wb-mrm2-mini_12/Input 2"] 
```

2022-09-06 13:11 UTC, matveevrj commented on wb-mrm2mini-gate-conrolling/gate-controlling.js
> +     if(dev["wb-mrm2-mini_12/Input 2"] == false) {
Ворота могут быть в промежуточном положении  (посередине), например, после принудительного останова кнопкой Стоп. Тогда нужно проверять если они Неоткрыты то открыть.

2022-09-06 13:11 UTC, matveevrj commented on wb-mrm2mini-gate-conrolling/gate-controlling.js
> +  if(dev ["wb-mrm2-mini_12/Input 1"] == false) {
Ворота могут быть в промежуточном положении  (посередине), например, после принудительного останова кнопкой Стоп. Тогда нужно проверять если они Неоткрыты то открыть.

2022-09-08 09:57 UTC, wb-adegtyarev requested changes
Оставил комментарии

2022-09-08 09:57 UTC, wb-adegtyarev commented on WM-MR6Cv3-gate-controlling/README.md
> +<p>Ссылка на статью <a href="https://wirenboard.com/ru/pages/gate_control/">Управление воротами</a>.</p>
тут разметка Murkdown, html надо убрать

2022-09-08 09:57 UTC, wb-adegtyarev commented on wb-mrm2mini-gate-conrolling/README.md
> +<p>Ссылка на статью <a href="https://wirenboard.com/ru/pages/gate_control/" >Управление воротами</a>.</p>
Аналогично, html теги убери и разметь Murkdown.

2022-09-08 09:57 UTC, wb-adegtyarev commented on WM-MR6Cv3-gate-controlling/WB-MR6Cv3-gate-controlling.js
> +
Тут и в другом скрипте лишний отступ

2022-09-08 09:57 UTC, wb-adegtyarev commented on WM-MR6Cv3-gate-controlling/WB-MR6Cv3-gate-controlling.js
> +  whenChanged: ["wb-mr6cv3_135/Input 0", "wb-mr6cv3_135/Input 1", "wb-mr6cv3_135/Input 2", "wb-mr6cv3_135/Input 3", "wb-mr6cv3_135/Input 4", "wb-mr6cv3_135/Input 5"],
В ситуациях, когда нам надо гарантированно поймать нажатие кнопки, лучше следить не за состоянием, а за счётчиком нужного выхода (counter).

Все потому, что нажатие довольно мимолётное событие и оно может случиться между опросами устройства и потеряется. А изменение счётчика гарантированно будет передано.

А зачем мы вообще тут смотрим за входами 4 и 5, если они не обрабатываются в скрипте?

Ещё, наверное, разнести бы обработку кнопок и датчиков в разные правила (не скрипты). Да, кода больше, но логически это вроде вернее и понятнее.

2022-09-09 07:42 UTC, wb-adegtyarev approved these changes

2022-09-09 07:43 UTC, merged